Repository sangmandu/Boostcamp_2st_Hot6, pull requests merged in 2021-08, with the labels that each got.

#3 Create pr.py
  Algorithm/EUNWOO/pr.py
Labels: 해결

#4 Create test.py
  Algorithm/BYEOLYI/test.py
Labels: 해결

#2 Create test.py
  Algorithm/HEERAK/1058.py
Labels: 해결

#6 Create test.py
  Algorithm/JAEHYEON/test.py
Labels: 해결

#5 Create asda
  Algorithm/Sangjun/asda
Labels: 해결

#7 1058. 친구
  Algorithm/SEONGWON/1058.py
Labels: 보통

#12 1058. 친구
  Algorithm/SANGMIN/1058.py
Labels: 보통

#19 1138. 한 줄로 서기
  Algorithm/HEERAK/1138.py
Labels: 어려움

#20 1138. 한 줄로 서기
  Algorithm/SANGMIN/1138.py
Labels: 보통

#27 2606. 바이러스 + 9204.체스
  Algorithm/SANGMIN/2606.py
  Algorithm/SANGMIN/9204.py
Labels: 보통

#24 2606. 바이러스 + 9204. 체스
  Algorithm/HEERAK/2606.py
  Algorithm/HEERAK/9204.py
Labels: 어려움

#29 2606. 바이러스 + 9204. 체스
  Algorithm/9204.py
  Algorithm/BYEOLYI/2606.py
Labels: 어려움, 생각중

#36 7562. 나이트의 이동 + 10026. 적록색약
  Algorithm/BYEOLYI/10026.py
  Algorithm/BYEOLYI/7562.py
Labels: 어려움

#35 7562. 나이트의 이동 + 10026. 적록색약
  Algorithm/SANGMIN/10026.py
  Algorithm/SANGMIN/7562.py
Labels: 보통

#39 5710. 전기 요금
  Algorithm/SANGMIN/5710.py
Labels: 보통

#51 9081. 단어 맞추기
  Algorithm/BYEOLYI/9081.py
Labels: 어려움

#44 9081. 단어 맞추기
  Algorithm/SANGMIN/9081.py
Labels: 보통

#61 3182. 한동이 + 1027. 고층 건물
  Algorithm/SANGMIN/1027.py
  Algorithm/SANGMIN/3182.py
Labels: 보통

#62 3182. 한동이 + 1027. 고층 건물
  Algorithm/HEERAK/1027.py
  Algorithm/HEERAK/3182.py
Labels: 보통

#66 1003.피보나치 함수 + 4150.피보나치 수
  Algorithm/SANGMIN/1003.py
  Algorithm/SANGMIN/4150.py
Labels: 쉬움

#68 1003. 피보나치 함수 + 4150. 피보나치 수
  Algorithm/BYEOLYI/1003.py
  Algorithm/BYEOLYI/4150.py
Labels: 보통

#70 1003. 피보나치 함수 + 4150. 피보나치 수
  Algorithm/HEERAK/1003.py
  Algorithm/HEERAK/4150.py
Labels: 보통

#73 7507. 올림픽 경기
  Algorithm/SANGMIN/7507.py
Labels: 보통

#74 7507. 올림픽 게임
  Algorithm/HEERAK/7507.py
Labels: 보통

#82 9009. 피보나치 + 18352. 특정 거리의 도시 찾기
  Algorithm/SANGMIN/18352.py
  Algorithm/SANGMIN/9009.py
Labels: 보통

#81 9009. 피보나치 + 18352. 특정 거리의 도시 찾기
  Algorithm/HEERAK/18352.py
  Algorithm/HEERAK/9009.py
Labels: 보통

#87 2636. 치즈 + 1987. 알파벳
  Algorithm/HEERAK/1987.py
  Algorithm/HEERAK/2636.py
Labels: 어려움

#88 2636. 치즈 + 1987. 알파벳
  Algorithm/SANGMIN/1987.py
  Algorithm/SANGMIN/2636.py
Labels: 어려움

#95 15787. 기차가 어둠을 헤치고 은하수를
  Algorithm/SANGMIN/15787.py
Labels: 쉬움

#94 15787. 기차가 어둠을 헤치고 은하수를
  Algorithm/HEERAK/15785.py
Labels: 쉬움

#100 14719. 빗물
  Algorithm/SANGMIN/14719.py
Labels: 보통

#114 21938. 영상처리
  Algorithm/SANGMIN/21938.py
Labels: 쉬움

#121 1600. 말이되고픈 원숭이 + 15566. 개구리 1
  Algorithm/SANGMIN/15566.py
  Algorithm/SANGMIN/1600.py
Labels: 보통, 이 문제 누가 골랐어요

#122 1600. 말이 되고픈 원숭이 + 15566. 개구리 1 못 풀음
  Algorithm/BYEOLYI/15566.py
  Algorithm/BYEOLYI/1600.py
Labels: 생각중

#120 1600. 말이되고픈 원숭이 + 15566. 개구리 1 못품
  Algorithm/HEERAK/15566.py
  Algorithm/HEERAK/1600.py
Labels: 어려움

#128 2491. 수열
  Algorithm/HEERAK/2491.py
Labels: 쉬움

#126 2491. 수열
  Algorithm/SANGMIN/2491.py
Labels: 쉬움
